version: "3.7"
services:
  web:
    build: .
    command: ["--host", "0.0.0.0"]
    environment:
      - FLASK_ENV=development
    links:
      - db
    ports:
      - "8080:5000"
    restart: always
  db:
    image: postgres:11.5-alpine
    restart: always
  adminer:
    image: adminer:4.7.2-standalone
    restart: always
    ports:
      - "9000:8080"
