version: "3.7"
services:
  web:
    build: .
    command: ["--host", "0.0.0.0", "--port", "8080"]
    environment:
      - FLASK_ENV=development
    expose:
      - "8080"
    links:
      - db
    ports:
      - "8080:8080"
  db:
    image: mongo:4.0.10