version: "3.7"
services:
  web:
    build: .
    command: ["--host", "0.0.0.0", "--port", "8080"]
    environment:
      - FLASK_ENV=development
    expose:
      - "8080"
    ports:
      - "8080:8080"
